### ISSUE TITLE
Resource endpoints fail with 404 due to incorrectly constructed URLs

### ISSUE THREAD

**Issue by adamsmith448** [Canner/keycloak-admin#5]
Thanks for this library which looks great! :)

I am having an issue running a simple quickstart to authenticate with keycloak and list clients:

```
#!/usr/bin/env node

import KcAdminClient from 'keycloak-admin';

async function main() {
    const kcAdminClient = new KcAdminClient({
        baseUrl: 'http://localhost:8081/keycloak/auth',
        realmName: 'realm'
    });

    await kcAdminClient.auth({
        username: 'username',
        password: 'password',
        grantType: 'password',
        clientId: 'admin-cli'
    });

    await kcAdminClient.clients.find()
        .catch(err => console.log(err));

}

main();
```

But on the `clients.find()` line I get an error
```
Error: Request failed with status code 404
```

Looking into the error object the request URL was
```
http://localhost:8081/keycloak/auth%5Cadmin%5Crealms%5Crealm%5Cclients
```
i.e. it seems the URL has been constructed and/or encoded incorrectly.

I am running the script via 
```
ts-node index.ts
```

Have you seen this before? Is there a known fix and/or workaround?

**Comment by adamsmith448** [comment]
Thanks for the quick response.
- OS is Windows 10
- Node & typescript versions:
```
>ts-node -v
ts-node v7.0.1
node v9.0.0
typescript v3.1.1
```

Regarding the baseUrl - we changed this in keycloak config as per https://stackoverflow.com/a/44627360

**Comment by wwwy3y3** [comment]
Hi @adamsmith448 

The problem is that windows use backslash in `path.join()`, which cause some problem at url parsing.

Would you mind use the latest version (1.6.3) to test again in your environment (Windows)?

I don't have windows env by my hand, so I have to rely on you to test for me :)

Thanks!

**Comment by adamsmith448** [comment]
Nice, that has fixed it, thank you!

Thanks for the quick response & fix :)

**Comment by wwwy3y3** [comment]
Glad to hear that 😀
